Importing Libraries

In [113]:
import numpy as np
import pandas as pd

Reading Data

In [142]:
TRAIN_FILE = "../data/train_data.txt"
data_raw = pd.read_csv(TRAIN_FILE,sep="\t", names=['Index','Label','Tweet'])
data_raw.head()
# need to Remove the Index 0

Index  Label                                              Tweet
0  Tweet index  Label                                         Tweet text
1            1      1  Sweet United Nations video. Just in time for C...
2            2      1  @mrdahl87 We are rumored to have talked to Erv...
3            3      1  Hey there! Nice to see you Minnesota/ND Winter...
4            4      0                3 episodes left I'm dying over here

# Data Preprocessing

In [143]:
data_raw = data_raw.drop(0,axis=0)
data_raw.head()

Index Label                                              Tweet
1     1     1  Sweet United Nations video. Just in time for C...
2     2     1  @mrdahl87 We are rumored to have talked to Erv...
3     3     1  Hey there! Nice to see you Minnesota/ND Winter...
4     4     0                3 episodes left I'm dying over here
5     5     1  I can't breathe! was chosen as the most notabl...

Removing @ Mark From Tweets

In [116]:
atmark_filtered_tweets=data_raw[~data_raw.Tweet.str.contains("@[\w]*")]
atmark_filtered_tweets.transpose()

1     \
Index                                                  1   
Label                                                  1   
Tweet  Sweet United Nations video. Just in time for C...   

                                                    3     \
Index                                                  3   
Label                                                  1   
Tweet  Hey there! Nice to see you Minnesota/ND Winter...   

                                      4     \
Index                                    4   
Label                                    0   
Tweet  3 episodes left I'm dying over here   

                                                    5     \
Index                                                  5   
Label                                                  1   
Tweet  I can't breathe! was chosen as the most notabl...   

                                                    6     \
Index                                                  6   
Label                                                  0   
Tweet  You're never too old for Footie Pajamas. http:...   

                                                    7     \
Index                                                  7   
Label                                                  1   
Tweet  Nothing makes me happier then getting on the h...   

                                                    8     \
Index                                                  8   
Label                                                  0   
Tweet  4:30 an opening my first beer now gonna be a l...   

                                                    11    \
Index                                                 11   
Label                                                  1   
Tweet  Oh, thank GOD - our entire office email system...   

                                                    12    \
Index                                                 12   
Label                                                  0   
Tweet  But instead, I'm scrolling through Facebook, I...   

                                                    14    \
Index                                                 14   
Label                                                  0   
Tweet  Cold or warmth both suffuse one's cheeks with ...   

                             ...                          \
Index                        ...                           
Label                        ...                           
Tweet                        ...                           

                                                    3804  \
Index                                               3821   
Label                                                  0   
Tweet  Chill #Repost #Dead #Not #Dominos #Haha 😂💀 htt...   

                                                    3805  \
Index                                               3822   
Label                                                  1   
Tweet  Someone I work w doesn't let his kids believe ...   

                                                    3806  \
Index                                               3823   
Label                                                  0   
Tweet  Check out my new post! MyFairDaily: 10 Things ...   

                                                    3807  \
Index                                               3824   
Label                                                  1   
Tweet  Obama whisked away to hospital, diagnosed with...   

                                                    3809  \
Index                                               3826   
Label                                                  0   
Tweet  Another one of our support vehicles modified f...   

                                           3810  \
Index                                      3827   
Label                                         1   
Tweet  Thanks for shutting the city down.. #not   

                                               

Removing Special Characters like emoji & Punctuation marks - here not removing the # value

In [117]:
#character_filtered_tweets = atmark_filtered_tweets.Tweet.str.replace("[^a-zA-Z]", "")
#character_filtered_tweets = atmark_filtered_tweets[atmark_filtered_tweets.Tweet.str.replace("[^a-zA-Z]", "")]
#character_filtered_tweets = atmark_filtered_tweets['Tweet'].str.replace("[^a-zA-Z]", " ")
#character_filtered_tweets = atmark_filtered_tweets['Tweet'.replace("[^a-zA-Z]", " ")]
character_filtered_tweets = atmark_filtered_tweets.replace(to_replace='[^a-zA-Z0-9#]', value='', regex=True)
#filtered_tweets = atmark_filtered_tweets.replace({'Tweets': '^a-zA-Z#'}, {'Tweets': ''}, regex=True)
character_filtered_tweets.transpose()

1     \
Index                                                  1   
Label                                                  1   
Tweet  SweetUnitedNationsvideoJustintimeforChristmas#...   

                                                   3     \
Index                                                 3   
Label                                                 1   
Tweet  HeythereNicetoseeyouMinnesotaNDWinterWeather#Not   

                               4     \
Index                             4   
Label                             0   
Tweet  3episodesleftImdyingoverhere   

                                                    5     \
Index                                                  5   
Label                                                  1   
Tweet  Icantbreathewaschosenasthemostnotablequoteofth...   

                                                    6     \
Index                                                  6   
Label                                                  0   
Tweet  YourenevertoooldforFootiePajamashttptcoElzGqsX2yQ   

                                                    7     \
Index                                                  7   
Label                                                  1   
Tweet  Nothingmakesmehappierthengettingonthehighwayan...   

                                                 8     \
Index                                               8   
Label                                               0   
Tweet  430anopeningmyfirstbeernowgonnabealongnightday   

                                                    11    \
Index                                                 11   
Label                                                  1   
Tweet  OhthankGODourentireofficeemailsystemisdownthed...   

                                                    12    \
Index                                                 12   
Label                                                  0   
Tweet  ButinsteadImscrollingthroughFacebookInstagrama...   

                                                    14    \
Index                                                 14   
Label                                                  0   
Tweet  Coldorwarmthbothsuffuseonescheekswithpinkcolou...   

                             ...                          \
Index                        ...                           
Label                        ...                           
Tweet                        ...                           

                                                    3804  \
Index                                               3821   
Label                                                  0   
Tweet  Chill#Repost#Dead#Not#Dominos#HahahttptcoSnUkk...   

                                                    3805  \
Index                                               3822   
Label                                                  1   
Tweet  SomeoneIworkwdoesntlethiskidsbelieveinSantabec...   

                                                    3806  \
Index                                               3823   
Label                                                  0   
Tweet  CheckoutmynewpostMyFairDaily10ThingsIveBeenLov...   

                                                    3807  \
Index                                               3824   
Label                                                  1   
Tweet  Obamawhiskedawaytohospitaldiagnosedwithacidref...   

                                                    3809  \
Index                                               3826   
Label                                                  0   
Tweet  AnotheroneofoursupportvehiclesmodifiedforIcela...   

                                   3810  \
Index                              3827   
Label                                 1   
Tweet  Thanksforshuttingthecitydown#not   

                                                    3812  \
Index                                               3829   
Lab

Removing Index Column - Not necessary for predection

In [118]:
data_cleaned = character_filtered_tweets.drop('Index',axis=1)
data_cleaned.transpose()

1     \
Label                                                  1   
Tweet  SweetUnitedNationsvideoJustintimeforChristmas#...   

                                                   3     \
Label                                                 1   
Tweet  HeythereNicetoseeyouMinnesotaNDWinterWeather#Not   

                               4     \
Label                             0   
Tweet  3episodesleftImdyingoverhere   

                                                    5     \
Label                                                  1   
Tweet  Icantbreathewaschosenasthemostnotablequoteofth...   

                                                    6     \
Label                                                  0   
Tweet  YourenevertoooldforFootiePajamashttptcoElzGqsX2yQ   

                                                    7     \
Label                                                  1   
Tweet  Nothingmakesmehappierthengettingonthehighwayan...   

                                                 8     \
Label                                               0   
Tweet  430anopeningmyfirstbeernowgonnabealongnightday   

                                                    11    \
Label                                                  1   
Tweet  OhthankGODourentireofficeemailsystemisdownthed...   

                                                    12    \
Label                                                  0   
Tweet  ButinsteadImscrollingthroughFacebookInstagrama...   

                                                    14    \
Label                                                  0   
Tweet  Coldorwarmthbothsuffuseonescheekswithpinkcolou...   

                             ...                          \
Label                        ...                           
Tweet                        ...                           

                                                    3804  \
Label                                                  0   
Tweet  Chill#Repost#Dead#Not#Dominos#HahahttptcoSnUkk...   

                                                    3805  \
Label                                                  1   
Tweet  SomeoneIworkwdoesntlethiskidsbelieveinSantabec...   

                                                    3806  \
Label                                                  0   
Tweet  CheckoutmynewpostMyFairDaily10ThingsIveBeenLov...   

                                                    3807  \
Label                                                  1   
Tweet  Obamawhiskedawaytohospitaldiagnosedwithacidref...   

                                                    3809  \
Label                                                  0   
Tweet  AnotheroneofoursupportvehiclesmodifiedforIcela...   

                                   3810  \
Label                                 1   
Tweet  Thanksforshuttingthecitydown#not   

                                                    3812  \
Label                                                  1   
Tweet  Gladtheresnotatyphoonwherewegoonholidayin4week...   

                                                    3815  \
Label                                                  0   
Tweet  wellnowthativelistenedtoallofintothewoodsimgoi...   

                                                    3816  \
Label                                                  0   
Tweet  Hummingbirds#Are#Not#Experts#at#Hovering#After...   

                                                    3817  
Label                                                  0  
Tweet  OnlythingmissingnowisasessionatthegymWanttodoe...  

[2 rows x 2264 columns]

# Defining Independent(X) & Dependent(Y) Variable

In [119]:
X = data_cleaned['Tweet']
Y = data_cleaned['Label']

Counter Vectorizing

In [120]:
from sklearn.feature_extraction.text import CountVectorizer
vc = CountVectorizer()
vc.fit(X)
X_coded = vc.transform(X)
X_coded = X_coded.toarray()
print(X_coded)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Label Encoder 

In [121]:
from sklearn import preprocessing
label_encode = preprocessing.LabelEncoder()
labels = np.unique(Y)
label_encode.fit(labels)
Y_coded = list(label_encode.transform(Y))
Y_coded = np.asarray(Y_coded)
print(Y_coded)

[1 1 0 ... 0 0 0]


# Model Building - RandomForest Classifier

In [122]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_coded, Y_coded, test_size=0.1,random_state=109) # 70% training and 30% test
#print(X_train)
#print(y_test)
model = RandomForestClassifier(n_estimators=3,min_samples_leaf=1)
# Train the model using the training sets
model.fit(X_train,y_train)
# Predicting for Testing Sets
y_pred = model.predict(X_test)

# Model Evaluation - RandomForest Classifier

In [123]:
from sklearn import metrics
print("Random Forest Classifier Accuracy:",metrics.accuracy_score(y_test, y_pred))

('Random Forest Classifier Accuracy:', 0.8766519823788547)


# Model Building - SVM

In [125]:
from sklearn import svm
model_svm = svm.SVC(gamma='scale')
# Train the model using the training sets
model_svm.fit(X_train,y_train)
# Predicting for Testing Sets
y_pred_svm = model.predict(X_test)

# Model Evaluation - SVM

In [126]:
print(" SVM Accuracy:",metrics.accuracy_score(y_test, y_pred_svm))

(' SVM Accuracy:', 0.8766519823788547)


# Testing - Testing for Only One Model Hence The Accuracy Equal

Single Line Testing 

In [136]:
test = ["But instead, I'm scrolling through Facebook, Instagram, and Twitter for hours on end, accomplishing nothing. #ironyT"]
test= vc.transform(test)
test = test.toarray()

In [137]:
y_pred = model.predict(test)
print(y_pred)

[0]


# Testing via the test_data.txt

In [148]:
TEST_FILE = "../data/test_data.txt"
data_raw_test = pd.read_csv(TEST_FILE,sep=",")
data_raw_test.head()

Index                                               Text
0      1  @Callisto1947 Can U Help?||More conservatives ...
1      2  Just walked in to #Starbucks and asked for a "...
2      3              #NOT GONNA WIN http://t.co/Mc9ebqjAqj
3      4  @mickymantell He is exactly that sort of perso...
4      5  So much #sarcasm at work mate 10/10 #boring 10...

In [149]:
data_raw_test

Index                                               Text
0        1  @Callisto1947 Can U Help?||More conservatives ...
1        2  Just walked in to #Starbucks and asked for a "...
2        3              #NOT GONNA WIN http://t.co/Mc9ebqjAqj
3        4  @mickymantell He is exactly that sort of perso...
4        5  So much #sarcasm at work mate 10/10 #boring 10...
5        6               Corny jokes are my absolute favorite
6        7  People complain about my backround pic and all...
7        8  @SR_Duncan @benpobjie Darn, my sock joke needs...
8        9  if Christian expects Fifa to sleep in my bed w...
9       10  People who tell people with anxiety to "just s...
10      11  Most important thing I've learned in school ht...
11      12  #OrionLaunch underway - yeah! #Orion http://t....
12      13  I love context and large ensemble Fridays!!!!!...
13      14  Oh boy... @masongoodman in the house. Warm up ...
14      15  LIAR, i've never denied the 532 murders in Chi...
15      16  Always classy, never trashy and just a little ...
16      17  you believe you can say something, provide no ...
17      18  @ALL #Not #Long To Go #Before #MainStream #Med...
18      19  @Praise1300 Re: Jamie Grace has Tourette's? Th...
19      20  @CorporalFrisk Guess they didn't get the memo ...
20      21  Exam na jud. Merry christmas. ||#Sarcasm|#Kill...
21      22  The definition of #IRONY would be if a 77-year...
22      23  Pretty excited about how you gave up on me. Fi...
23      24  Who told the #hipsters that #irony was a thing...
24      25              @bigedh456 u know that. How u doing??
25      26  @LukeLPearson hmm... let me think about that #...
26      27  If you wanna look like a badass, have drama on...
27      28  How dare Charles Barkley have an intelligent c...
28      29  @LaurenBailes I think the general rule is, if ...
29      30  Natalie Prass - Bird of Prey: http://t.co/n7Yg...
..     ...                                                ...
754    755  Re: prison book ban - Of course Grayling is al...
755    756  Rolled out of bed for closing.... #ilookreally...
756    757  Watching VT and Cincy - qb for VT with (GODS) ...
757    758  you seem super smart MT "@GrannyMarried: @Docj...
758    759                  @Nialljenk8 Cheers bro! Top man 🙋
759    760  Even getting cooked breakfast.. Hes defo up to...
760    761  ROFLMAO yeah, OOPS is right @Gumlegs @RBRNetwo...
761    762  Coin ! LeCoinCanard: Coin ! LeCoinCanard: Coin...
762    763               I really want to see Into The Woods!
763    764  @JoshuaSinghAIW that bump off the apron looked...
764    765  @GazGShore please make me smile this Xmas.. Fi...
765    766  @lawsondath92 Hope the header didn't mess up t...
766    767  If it's NOT? then it IS! Hand Crafted Artistic...
767    768  It's okay @TicketmasterCA I didn't really want...
768    769  I'll try to guess the ASCII symbols without my...
769    770  Hearing gun shots when I first wake up makes m...
770    771  Protesters upset over decision in chokehold de...
771    772  @classicdrwho247 Great,& not sure if i've seen...
772    773  #TGIF oh just kidding I have 30 mins from one ...
773    774  Just got yelled at by proxy. It's going to be ...
774    775  Lol everyday excuse the language #relationship...
775    776  Making the most out of my last vacation day. #...
776    777  What a lovely day to drive #not #boo #fog #wor...
777    778  So restaurants that thrive on the social natur...
778    779  This long drive home later in the snow is gonn...
779    780  If you drag yesterday into today, your tomorro...
780    781  Congrats to my fav @JennyBrew & her team & my ...
781    782  @allkpop: Jessica sheds tears at her fan signi...
782    783  #Irony: al jazeera is pro Anti - #GamerGate be...
783    784  #NOT ALL 👌 There good & bad in every occupatio...

[784 rows x 2 columns]

In [147]:
# atmark_filtered_tweets_test=data_raw_test[~data_raw_test.Text.str.contains("@[\w]*")]
# atmark_filtered_tweets_test.transpose()

1    \
Index                                                  2   
Text   Just walked in to #Starbucks and asked for a "...   

                                         2    \
Index                                      3   
Text   #NOT GONNA WIN http://t.co/Mc9ebqjAqj   

                                                     4    \
Index                                                  5   
Text   So much #sarcasm at work mate 10/10 #boring 10...   

                                        5    \
Index                                     6   
Text   Corny jokes are my absolute favorite   

                                                     6    \
Index                                                  7   
Text   People complain about my backround pic and all...   

                                                     8    \
Index                                                  9   
Text   if Christian expects Fifa to sleep in my bed w...   

                                                     9    \
Index                                                 10   
Text   People who tell people with anxiety to "just s...   

                                                     10   \
Index                                                 11   
Text   Most important thing I've learned in school ht...   

                                                     11   \
Index                                                 12   
Text   #OrionLaunch underway - yeah! #Orion http://t....   

                                                     12   \
Index                                                 13   
Text   I love context and large ensemble Fridays!!!!!...   

                             ...                          \
Index                        ...                           
Text                         ...                           

                                                     772  \
Index                                                773   
Text   #TGIF oh just kidding I have 30 mins from one ...   

                                                     773  \
Index                                                774   
Text   Just got yelled at by proxy. It's going to be ...   

                                                     774  \
Index                                                775   
Text   Lol everyday excuse the language #relationship...   

                                                     775  \
Index                                                776   
Text   Making the most out of my last vacation day. #...   

                                                     776  \
Index                                                777   
Text   What a lovely day to drive #not #boo #fog #wor...   

                                                     777  \
Index                                                778   
Text   So restaurants that thrive on the social natur...   

                                                     778  \
Index                                                779   
Text   This long drive home later in the snow is gonn...   

                                                     779  \
Index                                                780   
Text   If you drag yesterday into today, your tomorro...   

                                                     782  \
Index                                                783   
Text   #Irony: al jazeera is pro Anti - #GamerGate be...   

                                                     783  
Index                                                784  
Text   #NOT ALL 👌 There good & bad in every occupatio...  

[2 rows x 483 columns]

In [152]:
char_filtered = data_raw_test.replace(to_replace='[^a-zA-Z0-9#]', value='', regex=True)
char_filtered

Index                                               Text
0        1  Callisto1947CanUHelpMoreconservativesneededon#...
1        2  Justwalkedinto#Starbucksandaskedforatallblonde...
2        3                      #NOTGONNAWINhttptcoMc9ebqjAqj
3        4      mickymantellHeisexactlythatsortofpersonWeirdo
4        5  Somuch#sarcasmatworkmate1010#boring100#deadmat...
5        6                    Cornyjokesaremyabsolutefavorite
6        7  PeoplecomplainaboutmybackroundpicandallIfeelis...
7        8         SRDuncanbenpobjieDarnmysockjokeneedsfixing
8        9  ifChristianexpectsFifatosleepinmybedwithmetoni...
9       10  Peoplewhotellpeoplewithanxietytojuststopworryi...
10      11  MostimportantthingIvelearnedinschoolhttptcoTvf...
11      12    #OrionLaunchunderwayyeah#Orionhttptco0Qkv1yq8T0
12      13  IlovecontextandlargeensembleFridaysDermymostfa...
13      14  OhboymasongoodmaninthehouseWarmuptheDJboothAnn...
14      15  LIARiveneverdeniedthe532murdersinChicagoin2012...
15      16         Alwaysclassynevertrashyandjustalittlesassy
16      17  youbelieveyoucansaysomethingprovidenoproofandi...
17      18  ALL#Not#LongToGo#Before#MainStream#Media#Pitch...
18      19  Praise1300ReJamieGracehasTourettesThanksforsha...
19      20  CorporalFriskGuesstheydidntgetthememoregnonnuc...
20      21       ExamnajudMerrychristmas#Sarcasm#KillUsSlowly
21      22  Thedefinitionof#IRONYwouldbeifa77yearoldrapper...
22      23  PrettyexcitedabouthowyougaveuponmeFileUnder#sa...
23      24  Whotoldthe#hipstersthat#ironywasathingoftheCli...
24      25                        bigedh456uknowthatHowudoing
25      26         LukeLPearsonhmmletmethinkaboutthat#sarcasm
26      27  Ifyouwannalooklikeabadasshavedramaonsocialmedi...
27      28  HowdareCharlesBarkleyhaveanintelligentconversa...
28      29  LaurenBailesIthinkthegeneralruleisifitsopenall...
29      30  NataliePrassBirdofPreyhttptcon7YgEkpr4lviaYouTube
..     ...                                                ...
754    755  ReprisonbookbanOfcourseGraylingisalsotryingtob...
755    756       Rolledoutofbedforclosing#ilookreallygood#not
756    757  WatchingVTandCincyqbforVTwithGODSdownleftarmGI...
757    758  youseemsupersmartMTGrannyMarriedDocjpJoAnnEile...
758    759                          Nialljenk8CheersbroTopman
759    760     EvengettingcookedbreakfastHesdefouptosomething
760    761  ROFLMAOyeahOOPSisrightGumlegsRBRNetwork1blackt...
761    762  CoinLeCoinCanardCoinLeCoinCanardCoinhaveawanko...
762    763                       IreallywanttoseeIntoTheWoods
763    764  JoshuaSinghAIWthatbumpofftheapronlookedlikeith...
764    765  GazGShorepleasemakemesmilethisXmasFirstXmaswit...
765    766     lawsondath92Hopetheheaderdidntmessupthatbarnet
766    767  IfitsNOTthenitISHandCraftedArtisticallyFashion...
767    768  ItsokayTicketmasterCAIdidntreallywanttoseemyid...
768    769  IlltrytoguesstheASCIIsymbolswithoutmyadminshel...
769    770  HearinggunshotswhenIfirstwakeupmakesmefeellike...
770    771  Protestersupsetoverdecisioninchokeholddeathtak...
771    772  classicdrwho247Greatnotsureifiveseenthatactual...
772    773  #TGIFohjustkiddingIhave30minsfromonejobtothene...
773    774  JustgotyelledatbyproxyItsgoingtobeanexcellentd...
774    775  Loleverydayexcusethelanguage#relationships#men...
775    776  Makingthemostoutofmylastvacationday#not#tvands...
776    777  Whatalovelydaytodrive#not#boo#fog#workhttptcot...
777    778  Sorestaurantsthatthriveonthesocialnatureofeati...
778    779  Thislongdrivehomelaterinthesnowisgonnabeshweee...
779    780  Ifyoudragyesterdayintotodayyourtomorrowcannotb...
780    781  CongratstomyfavJennyBrewherteammybirthplacetea...
781    782  allkpopJessicashedstearsatherfansigningeventht...
782    783  #IronyaljazeeraisproAnti#GamerGatebecausefemin...
783    784  #NOTALLTheregoodbadineveryoccupationrace#StopL...

[784 rows x 2 columns]

ConvertTo String for Testing

In [153]:
string_converted = char_filtered['Text'].astype('|S')
string_converted

0      Callisto1947CanUHelpMoreconservativesneededon#...
1      Justwalkedinto#Starbucksandaskedforatallblonde...
2                          #NOTGONNAWINhttptcoMc9ebqjAqj
3          mickymantellHeisexactlythatsortofpersonWeirdo
4      Somuch#sarcasmatworkmate1010#boring100#deadmat...
5                        Cornyjokesaremyabsolutefavorite
6      PeoplecomplainaboutmybackroundpicandallIfeelis...
7             SRDuncanbenpobjieDarnmysockjokeneedsfixing
8      ifChristianexpectsFifatosleepinmybedwithmetoni...
9      Peoplewhotellpeoplewithanxietytojuststopworryi...
10     MostimportantthingIvelearnedinschoolhttptcoTvf...
11       #OrionLaunchunderwayyeah#Orionhttptco0Qkv1yq8T0
12     IlovecontextandlargeensembleFridaysDermymostfa...
13     OhboymasongoodmaninthehouseWarmuptheDJboothAnn...
14     LIARiveneverdeniedthe532murdersinChicagoin2012...
15            Alwaysclassynevertrashyandjustalittlesassy
16     youbelieveyoucansaysomethingprovidenoproofandi...
17     ALL#Not#LongToGo#Before#

In [154]:
prediction_list = []
for i in range(len(char_filtered)):
 #print(string_converted.iloc[i])
 test = [string_converted.iloc[i]]
 test= vc.transform(test)
 test = test.toarray()
 y_pred = model.predict(test)
 intval = ''.join([str(i) for i in y_pred]) 
 prediction_list.append(intval)
    
#print(prediction_list)
col_prediction = prediction_list
char_filtered['Label'] = (col_prediction) 
char_filtered.head()

Index                                               Text Label
0      1  Callisto1947CanUHelpMoreconservativesneededon#...     0
1      2  Justwalkedinto#Starbucksandaskedforatallblonde...     1
2      3                      #NOTGONNAWINhttptcoMc9ebqjAqj     0
3      4      mickymantellHeisexactlythatsortofpersonWeirdo     0
4      5  Somuch#sarcasmatworkmate1010#boring100#deadmat...     1

# Writing Predicted Data To a File

In [155]:
sample_prediction =char_filtered[['Label']]
sample_prediction.head()

Label
0     0
1     1
2     0
3     0
4     1

In [156]:
PREDICT_FILE = "../data/predict_data.csv"
sample_prediction.to_csv(PREDICT_FILE, sep=',', encoding='utf-8')